dtb-$(CONFIG_SOC_IMX7D) += \
	imx7d-cl-som-imx7.dtb \
 	imx7d-sbc-imx7.dtb \
	imx7d-sbc-imx7-lvds.dtb \
	imx7d-sbc-imx7-m4.dtb \
	imx7d-sbc-iot-imx7.dtb \
	imx7d-sbc-iot-imx7-can.dtb \
	imx7d-sbc-iot-imx7-rs485-hdx.dtb
