dtb-$(CONFIG_SOC_IMX6Q) += \
	imx6dl-cm-fx6.dtb \
	imx6dl-sbc-fx6.dtb \
	imx6dl-sbc-fx6-hdmi.dtb \
	imx6dl-sbc-fx6m.dtb \
	imx6dl-sbc-fx6-mipi.dtb \
	imx6q-cm-fx6.dtb \
	imx6q-sbc-fx6-1-hdmi-2-ldb.dtb \
	imx6q-sbc-fx6-1-ldb-2-hdmi.dtb \
	imx6q-sbc-fx6.dtb \
	imx6q-sbc-fx6-hdmi.dtb \
	imx6q-sbc-fx6-lcd-640x240-51.dtb \
	imx6q-sbc-fx6-ldb-640x240-51.dtb \
	imx6q-sbc-fx6-ldb-640x240-63.dtb \
	imx6q-sbc-fx6-ldb-640x240-65.dtb \
	imx6q-sbc-fx6-ldb-800x480-60.dtb \
	imx6q-sbc-fx6m.dtb \
	imx6q-sbc-fx6-mipi.dtb \
	imx6q-sbc-fx6-multi.dtb

always      := $(dtb-y)
subdir-y    := $(dtb-dirs)
clean-files := *.dtb
