dtb-$(CONFIG_ARCH_MXC) += iot-gate-imx8plus.dtb
dtb-$(CONFIG_ARCH_MXC) += iot-gate-imx8plus-usbdev.dtb
dtb-$(CONFIG_ARCH_MXC) += iot-gate-imx8plus-m2adc.dtb
dtb-$(CONFIG_ARCH_MXC) += iot-gate-imx8plus-m2emmc.dtb
dtb-$(CONFIG_ARCH_MXC) += iot-gate-imx8plus-m2tpm.dtb
dtb-$(CONFIG_ARCH_MXC) += iot-gate-imx8plus-brkout_pwm_gpio.dtb
