# i.MX9
dtb-$(CONFIG_SOC_IMX9) += sbc-mcm-imx93.dtb
dtb-$(CONFIG_SOC_IMX9) += mcm-imx93-lpspi.dtb
dtb-$(CONFIG_SOC_IMX9) += mcm-imx93-lpspi-slave.dtb
dtb-$(CONFIG_SOC_IMX9) += mcm-imx93-thermal.dtb
# i.MX9 overlays
dtb-$(CONFIG_SOC_IMX9) += mcm-imx93-lvds-overlay.dtbo
dtb-$(CONFIG_SOC_IMX9) += mcm-imx93-thermal-overlay.dtbo
