dtb-$(CONFIG_ARCH_MXC) += cl-som-imx8.dtb
dtb-$(CONFIG_ARCH_MXC) += sbc-imx8.dtb
dtb-$(CONFIG_ARCH_MXC) += sbc-imx8-thermal.dtb
dtb-$(CONFIG_ARCH_MXC) += sbc-imx8-bluetooth.dtb
dtb-$(CONFIG_ARCH_MXC) += sbc-imx8-no-edid.dtb
dtb-$(CONFIG_ARCH_MXC) += sbc-imx8-dp.dtb
dtb-$(CONFIG_ARCH_MXC) += sbc-imx8-m4.dtb
dtb-$(CONFIG_ARCH_MXC) += sbc-imx8-no-wp.dtb
dtb-$(CONFIG_ARCH_MXC) += sbc-imx8-emmc-low.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
