DTC_FLAGS := -@

dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus.dtb
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus_mipi-csi1.dtb
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus_mipi-csi1-ar1335-mcu.dtb

som-imx8m-plus_mipi-csi1-imx219-dtbs := som-imx8m-plus.dtb som-imx8m-plus_mipi-csi1-imx219.dtbo
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus_mipi-csi1-imx219.dtb

som-imx8m-plus_mipi-csi1-ov5647-dtbs := som-imx8m-plus.dtb som-imx8m-plus_mipi-csi1-ov5647.dtbo
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus_mipi-csi1-ov5647.dtb

som-imx8m-plus_mipi-csi2-ov5647-dtbs := som-imx8m-plus.dtb som-imx8m-plus_mipi-csi2-ov5647.dtbo
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus_mipi-csi2-ov5647.dtb

# Dual imx219 setup
som-imx8m-plus_mipi-csi1-csi2-dtbs := som-imx8m-plus.dtb som-imx8m-plus_mipi-csi1-imx219.dtbo som-imx8m-plus_mipi-csi2-imx219.dtbo
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus_mipi-csi1-csi2.dtb

dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus_mipi-csi1-ar0234.dtb
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus_mipi-csi1-ar0521.dtb
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus_mipi-csi2.dtb
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus_mipi-csi2-ar1335-mcu.dtb
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus_mipi-csi2-ar0234.dtb
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus_mipi-csi2-ar0521.dtb
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus-headless.dtb
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus-hdmi.dtb
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus-lvds.dtb
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus-mipi.dtb
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus-rpmsg.dtb
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus-thermal.dtb
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus-usbdev.dtb
# overlays
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus-mipi-overlay.dtbo
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus-lvds-overlay.dtbo
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus-hdmi-overlay.dtbo
