DTC_FLAGS := -@

dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus-headless.dtb

# hdmi
som-imx8m-plus-hdmi-dtbs := som-imx8m-plus-headless.dtb som-imx8m-plus-hdmi.dtbo
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus-hdmi.dtb

# lvds
som-imx8m-plus-lvds-dtbs := som-imx8m-plus-headless.dtb som-imx8m-plus-lvds.dtbo
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus-lvds.dtb

# mipi
som-imx8m-plus-mipi-dtbs := som-imx8m-plus-headless.dtb som-imx8m-plus-mipi.dtbo
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus-mipi.dtb

# all heads
som-imx8m-plus-dtbs := som-imx8m-plus-headless.dtb som-imx8m-plus-mipi.dtbo som-imx8m-plus-lvds.dtbo som-imx8m-plus-hdmi.dtbo
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus.dtb

# rpmsg
som-imx8m-plus-rpmsg-dtbs :=som-imx8m-plus.dtb som-imx8m-plus-rpmsg.dtbo
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus-rpmsg.dtb

# thermal
som-imx8m-plus-thermal-dtbs := som-imx8m-plus.dtb som-imx8m-plus-thermal.dtbo
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus-thermal.dtb

# usbdev
som-imx8m-plus-usbdev-dtbs := som-imx8m-plus.dtb som-imx8m-plus-usbdev.dtbo
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus-usbdev.dtb

# csi1
som-imx8m-plus_mipi-csi1-ar1335-af-dtbs := som-imx8m-plus.dtb som-imx8m-plus_mipi-csi1-ar1335-af.dtbo
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus_mipi-csi1-ar1335-af.dtb

som-imx8m-plus_mipi-csi1-ar1335-mcu-dtbs := som-imx8m-plus.dtb som-imx8m-plus_mipi-csi1-ar1335-mcu.dtbo
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus_mipi-csi1-ar1335-mcu.dtb

som-imx8m-plus_mipi-csi1-ar0234-dtbs := som-imx8m-plus.dtb som-imx8m-plus_mipi-csi1-ar0234.dtbo
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus_mipi-csi1-ar0234.dtb

som-imx8m-plus_mipi-csi1-ar0521-dtbs := som-imx8m-plus.dtb som-imx8m-plus_mipi-csi1-ar0521.dtbo
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus_mipi-csi1-ar0521.dtb

som-imx8m-plus_mipi-csi1-imx219-dtbs := som-imx8m-plus.dtb som-imx8m-plus_mipi-csi1-imx219.dtbo
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus_mipi-csi1-imx219.dtb

som-imx8m-plus_mipi-csi1-ov5647-dtbs := som-imx8m-plus.dtb som-imx8m-plus_mipi-csi1-ov5647.dtbo
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus_mipi-csi1-ov5647.dtb

# csi2
som-imx8m-plus_mipi-csi2-ar1335-af-dtbs := som-imx8m-plus.dtb som-imx8m-plus_mipi-csi2-ar1335-af.dtbo
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus_mipi-csi2-ar1335-af.dtb

som-imx8m-plus_mipi-csi2-ar1335-mcu-dtbs := som-imx8m-plus.dtb som-imx8m-plus_mipi-csi2-ar1335-mcu.dtbo
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus_mipi-csi2-ar1335-mcu.dtb

som-imx8m-plus_mipi-csi2-ar0234-dtbs := som-imx8m-plus.dtb som-imx8m-plus_mipi-csi2-ar0234.dtbo
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus_mipi-csi2-ar0234.dtb

som-imx8m-plus_mipi-csi2-ar0521-dtbs := som-imx8m-plus.dtb som-imx8m-plus_mipi-csi2-ar0521.dtbo
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus_mipi-csi2-ar0521.dtb

som-imx8m-plus_mipi-csi2-imx219-dtbs := som-imx8m-plus.dtb som-imx8m-plus_mipi-csi2-imx219.dtbo
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus_mipi-csi2-imx219.dtb

som-imx8m-plus_mipi-csi2-ov5647-dtbs := som-imx8m-plus.dtb som-imx8m-plus_mipi-csi2-ov5647.dtbo
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus_mipi-csi2-ov5647.dtb

# Dual imx219 setup
som-imx8m-plus_mipi-csi1-csi2-dtbs := som-imx8m-plus.dtb som-imx8m-plus_mipi-csi1-imx219.dtbo som-imx8m-plus_mipi-csi2-imx219.dtbo
dtb-$(CONFIG_ARCH_MXC) += som-imx8m-plus_mipi-csi1-csi2.dtb
