DTC_FLAGS := -@

dtb-$(CONFIG_ARCH_MXC) += ucm-imx95-som.dtb

ucm-imx95-dtbs := ucm-imx95-som.dtb \
		imx95-lvds.dtbo \
		imx95-wm8962.dtbo

dtb-$(CONFIG_ARCH_MXC) += ucm-imx95.dtb

ucm-imx95-rpmsg-dtbs := ucm-imx95-som.dtb \
		imx95-rpmsg.dtbo

dtb-$(CONFIG_ARCH_MXC) += ucm-imx95-rpmsg.dtb

ucm-imx95-evk-csi1-ap1302-dtbs := ucm-imx95-som.dtb \
		imx95-csi1-ap1302.dtbo

dtb-$(CONFIG_ARCH_MXC) += ucm-imx95-evk-csi1-ap1302.dtb

ucm-imx95-evk-csi2-ap1302-dtbs := ucm-imx95-som.dtb \
		imx95-csi2-ap1302.dtbo

dtb-$(CONFIG_ARCH_MXC) += ucm-imx95-evk-csi2-ap1302.dtb
