--- arch/arm64/boot/dts/compulab/Makefile
+++ arch/arm64/boot/dts/compulab/Makefile
@@ -1,4 +1,11 @@
 dtb-$(CONFIG_ARCH_MXC) += ucm-imx8m-mini.dtb
+dtb-$(CONFIG_ARCH_MXC) += mcm-imx8m-mini.dtb
+dtb-$(CONFIG_ARCH_MXC) += mcm-imx8m-mini-m4.dtb
+dtb-$(CONFIG_ARCH_MXC) += mcm-imx8m-mini-thermal.dtb
+dtb-$(CONFIG_ARCH_MXC) += sbc-mcm-imx8m-mini.dtb
+dtb-$(CONFIG_ARCH_MXC) += sbc-mcm-imx8m-mini-rs485.dtb
+dtb-$(CONFIG_ARCH_MXC) += sbc-mcm-imx8m-mini-spidev.dtb
+dtb-$(CONFIG_ARCH_MXC) += sbc-mcm-imx8m-mini-input.dtb
 
 always-y         := $(dtb-y)
 subdir-y       := $(dts-dirs)
