dtb-$(CONFIG_ARCH_FSL_IMX8MQ) += cl-som-imx8.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8MQ) += sbc-imx8.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8MQ) += sbc-imx8-thermal.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8MQ) += sbc-imx8-bluetooth.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8MQ) += sbc-imx8-lvds-dcss.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8MQ) += sbc-imx8-lvds-lcdif.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8MQ) += sbc-imx8-dual.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8MQ) += sbc-imx8-no-edid.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
