DTC_FLAGS := -@

dtb-$(CONFIG_ARCH_MXC) += mcm-imx95-sbc.dtb

mcm-imx95-rpmsg-dtbs := mcm-imx95-sbc.dtb \
		imx95-rpmsg.dtbo

dtb-$(CONFIG_ARCH_MXC) += mcm-imx95-rpmsg.dtb

mcm-imx95-evk-csi1-ap1302-dtbs := mcm-imx95-sbc.dtb \
		imx95-csi1-ap1302.dtbo

dtb-$(CONFIG_ARCH_MXC) += mcm-imx95-evk-csi1-ap1302.dtb

mcm-imx95-evk-csi2-ap1302-dtbs := mcm-imx95-sbc.dtb \
		imx95-csi2-ap1302.dtbo

dtb-$(CONFIG_ARCH_MXC) += mcm-imx95-evk-csi2-ap1302.dtb
